export default{
    name:"comment",
    type:"document",
    title:"Comments",
    fields:[
        {
            name:"name",
            type:"string",
        },
        {
            name:"approved",
            Title:"Approved",
            type:"boolean",
        },
        {
            name:"comment",
            type:"text",
        },
        {
            name:"email",
            type:"string",
        },
        {
            name:"post",
            type:"reference",
            to:[{type:"post"}]
        }
    ]
}